### ISSUE TITLE
Cannot resolve from repository

### ISSUE THREAD

**Issue by hanxue** [melezov/sbt-sh#1]
Hello,

I used the following in my sbt file, but could not get them to resolve

``` scala
resolvers += "Element Releases" at "http://repo.element.hr/nexus/content/repositories/releases/"

addSbtPlugin("hr.element.xsbt" % "xsbt-sh" % "0.1.0")
```

Checking at the website, I cannot find any `xsbt-sh` sub-directory at http://repo.element.hr/nexus/content/repositories/releases/hr/element/

Do I need to use a different syntax, e.g. 

`addSbtPlugin("hr.element.xsbt" % "xsbt" % "0.13")`

**Comment by melezov** [comment]
I'll publish "0.1.0" to Sonatype today so that we don't need to add the custom resolver

**Comment by melezov** [comment]
Yesterday was today, so I published to BinTray.  
You should now be able to resolve without adding any custom repositories:

`addSbtPlugin("com.oradian.sbt" % "sbt-sh" % "0.1.0")`
